apiVersion: v1
kind: Pod
metadata:
  name: openmole-connect
spec:
  containers:
  - name: openmole-connect
    image: openmole-connect:0.6-SNAPSHOT
    args:
      - --config-file
      - "/etc/connect-config/config.yml"
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: connect-config
        mountPath: "/etc/connect-config"
        readOnly: true
  volumes:
    - name: connect-config
      configMap:
        name: connect-config

#kubectl run openmole-connect --port 8080 --image=openmole-connect:0.6-SNAPSHOT -- --salt some-salt --kube-off --secret some-secret --openmole-test="http://$OPENMOLE_IP:8080/"
#sleep 3
