apiVersion: v1
kind: Namespace
metadata:
  name: openmole
  labels:
    name: openmole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openmole-admin-sa
  namespace: openmole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openmole-admin-role
  namespace: openmole
rules:
- apiGroups:
  - "*"
  resources: 
  - "*" #["pods", "deployments" ]
  verbs: 
  - "*" #["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openmole-role-binding
  namespace: openmole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openmole-admin-role
subjects:
- kind: ServiceAccount
  name: openmole-admin-sa
  namespace: openmole
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openmole-storage
  namespace: openmole
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
---
apiVersion: v1
data:
  config.yml: |
    salt: "some-salt"
    secret: "some-secret"
    kube:
     storageClassName: openmole-storage
     storageSize: 20480
    openmole:
      versionHistory: 3
      minimumVersion: 17
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: connect-config
  namespace: openmole
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connect-pv-claim
  namespace: openmole
spec:
  storageClassName: openmole-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: openmole-connect
  namespace: openmole
  labels:
    app.kubernetes.io/name: openmole-connect
spec:
  containers:
  - name: openmole-connect
    image: openmole/openmole-connect:1.0-SNAPSHOT
    imagePullPolicy: "Always"
    args:
      - --config-file
      - "/etc/connect-config/config.yml"
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: connect-config
        mountPath: "/etc/connect-config"
        readOnly: true
      - mountPath: "/home/demiourgos728"
        name: connect-pv-storage
  securityContext:
    fsGroup: 1001
  volumes:
    - name: connect-config
      configMap:
        name: connect-config
    - name: connect-pv-storage
      persistentVolumeClaim:
        claimName: connect-pv-claim
  serviceAccountName: openmole-admin-sa
---
apiVersion: v1
kind: Service
metadata:
  name: openmole-connect-service
  namespace: openmole
spec:
  selector:
    app.kubernetes.io/name: openmole-connect
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openmole-connect-ingress
  namespace: openmole
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: openmole-connect-service
      port:
        number: 8080
#    - host: online.openmole.org
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: openmole-connect-service
#                port:
#                  number: 8080
